name: Rust

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [armv7-unknown-linux-gnueabihf, aarch64-unknown-linux-gnu]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      uses: houseabsolute/actions-rust-cross@v0.0.12
      with:
        command: build
        target: ${{matrix.target}}
        args: "--locked"
    - name: Run tests
      uses: houseabsolute/actions-rust-cross@v0.0.12
      with:
        command: test
        target: ${{matrix.target}}
        args: "--locked"
    - uses: Swatinem/rust-cache@v2
